ci: attempt to speed up ci

diff --git a/.github/workflows/run_pytests.yaml b/.github/workflows/run_pytests.yaml
--- a/.github/workflows/run_pytests.yaml
+++ b/.github/workflows/run_pytests.yaml
@@ -33,26 +33,28 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install git+https://github.com/ESSS/conda-devenv.git@2.1.1
-        python -m conda_devenv.devenv --env PADO_DEVEL=TRUE --env PADO_DEVEL_CI=TRUE --file environment.devenv.yml --print > environment.yml
+        python -m conda_devenv.devenv --env PADO_DEVEL_CI=TRUE --file environment.devenv.yml --print > environment.yml
 
     - name: Cache conda
-      uses: actions/cache@v1
+      uses: actions/cache@v2
       env:
-        # Increase this value to reset cache if etc/example-environment.yml has not changed
         CACHE_NUMBER: 0
       with:
         path: ~/conda_pkgs_dir
-        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}
+        key: conda-pkgs-${{ runner.os }}-${{ runner.arch }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.devenv.yml') }}
 
     - name: Setup conda
       uses: conda-incubator/setup-miniconda@v2
       with:
         environment-file: environment.yml
-        python-version: ${{ matrix.python-version }}
-        auto-update-conda: true
         activate-environment: pado
+        python-version: ${{ matrix.python-version }}
+        miniforge-variant: Mambaforge
+        mamba-version: "*"
+        use-mamba: true
+        channels: conda-forge
+        channel-priority: strict
         use-only-tar-bz2: true
-        auto-activate-base: false
 
     - name: Verify conda installation
       shell: bash -l {0}
@@ -64,7 +66,7 @@ jobs:
       shell: bash -l {0}
       run: |
         if [ "$RUNNER_OS" == "Windows" ]; then
-          pytest --cov=pado || echo "Windows failure"
+          pytest --cov=pado || echo "::warning:: windows tests failure"
         else
           pytest --cov=pado
         fi
