ci: fix coverage reports

diff --git a/.github/workflows/run_pytests.yaml b/.github/workflows/run_pytests.yaml
--- a/.github/workflows/run_pytests.yaml
+++ b/.github/workflows/run_pytests.yaml
@@ -37,7 +37,7 @@ jobs:
       shell: bash -l {0}
       run: |
         if [ "$RUNNER_OS" == "Windows" ]; then
-          pytest --cov=pado ./pado/tests || echo "::warning:: Windows tests failed, but failure is ignored"
+          pytest --cov=pado ./pado || echo "::warning:: Windows tests failed, but failure is ignored"
         else
-          pytest --cov=pado ./pado/tests
+          pytest --cov=pado ./pado
         fi
